### ISSUE TITLE
Special Feature

### ISSUE THREAD

**Issue by MacKarp** [MacKarp/ICE_CREAM_Project#2]
What special feature we will add to our core app

**Comment by Tuchtuch** [comment]
How about simple Expert system? User answers for a few questions and app suggests desired flavor?

**Comment by MacKarp** [comment]
Maybe we should do social media message generator

**Comment by LK-Herman** [comment]
I think the expert system sounds like a good idea. The user can go through the survey once and set his personal preferences / tastes. He can always repeat the survey if his preferences change. After logging in, ice cream suggestions (according to preferences) will be displayed on his home page in a proper order.

**Comment by LK-Herman** [comment]
As I remember, Adam/Tuchtuch made a fine expert system last year :)

**Comment by MacKarp** [comment]
Yes, you are right
