### ISSUE TITLE
Standard Features List

### ISSUE THREAD

**Issue by LK-Herman** [MacKarp/ICE_CREAM_Project#8]
List of standard functionalities. All the things the app should have ...

**Comment by MacKarp** [comment]
This should be core functionality:
- [x] List of ice cream shops
- [x] filtering list by taste
- [x] filtering list by location
- [x] Adding new ice cream shop page
- [x] Edit ice cream shop page
- [x] Delete ice cream shop page
- [x] Some user login system

**Comment by LK-Herman** [comment]
[ICECREAM Standard features.pdf](https://github.com/MacKarp/ICE_CREAM_Project/files/7470536/ICECREAM.Standard.features.pdf)
